# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guerreiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('telefone', models.CharField(max_length=50, null=True)),
                ('endereco', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=50, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('contato_emergencia', models.CharField(max_length=150)),
                ('tipo_sanguineo', models.CharField(max_length=3, null=True)),
                ('alergia_medicamento', models.CharField(max_length=100, null=True)),
                ('mascara', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')])),
                ('luva', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')])),
                ('marcador', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')])),
                ('farda', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')])),
                ('radio', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')])),
                ('colete', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')])),
            ],
        ),
    ]
